In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [2]:
df = pd.read_csv('data/stud.csv')

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
X = df.drop(columns=['math_score'])
y = df['math_score']

In [5]:
X.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [6]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [7]:
# Create  column transformer With 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OnehotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features)
    ]
)

/var/folders/w6/4s__vlwd3qd6fb66nzf4ts6r0000gn/T/ipykernel_79019/4066756903.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = X.select_dtypes(include="object").columns

In [8]:
X = preprocessor.fit_transform(X)

In [9]:
X

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.19399858,  0.39149181],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         1.42747598,  1.31326868],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.77010859,  1.64247471],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.12547206, -0.20107904],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.60515772,  0.58901542],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
         1.15336989,  1.18158627]], shape=(1000, 19))

In [10]:
X.shape

(1000, 19)

In [11]:
## Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
X_train.shape, X_test.shape

((800, 19), (200, 19))

## Create and Evaluate function to print all metrics after model training

In [13]:
def evaluate_model(actual, predicted):
    mae = mean_absolute_error(actual, predicted)
    mse = mean_squared_error(actual, predicted)
    rmse = np.sqrt(mse)
    r2_score_value = r2_score(actual, predicted)
    return mae, rmse, r2_score_value

In [15]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbours Regression": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random forest Regressor": RandomForestRegressor(),
    "XGBoostRegressor": XGBRegressor(),
    "CatBoosting Regressor": CatBoostRegressor(),
    "Adaboost Regressor": AdaBoostRegressor()
}

model_list = []
r2_list = []


for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) ## Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate the train and test dataset
    model_train_mae, model_train_rmse, mode_train_r2_score = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2_score = evaluate_model(y_test, y_test_pred)

    model_name = list(models.keys())[i]
    print(model_name)

    model_list.append(model_name)

    print("Model performance for training set")
    print("- Root mean squared error: {:.4f}".format(model_train_mae))
    print("- Mean absolute error: {:.4f}".format(model_train_rmse))
    print("- R2 score: {:.4f}".format(mode_train_r2_score))

    print("----------------------")

    print("Model performace for test set")
    print("- Root mean squared error: {:.4f}".format(model_test_mae))
    print("- Mean absolute error: {:.4f}".format(model_test_rmse))
    print("- R2 score: {:.4f}".format(model_test_r2_score))
    r2_list.append(model_test_r2_score)

    print('='*35)
    print('\n')

Linear Regression
Model performance for training set
- Root mean squared error: 4.2667
- Mean absolute error: 5.3231
- R2 score: 0.8743
----------------------
Model performace for test set
- Root mean squared error: 4.2148
- Mean absolute error: 5.3940
- R2 score: 0.8804
===================================


Lasso
Model performance for training set
- Root mean squared error: 5.2063
- Mean absolute error: 6.5938
- R2 score: 0.8071
----------------------
Model performace for test set
- Root mean squared error: 5.1579
- Mean absolute error: 6.5197
- R2 score: 0.8253
===================================


Ridge
Model performance for training set
- Root mean squared error: 4.2650
- Mean absolute error: 5.3233
- R2 score: 0.8743
----------------------
Model performace for test set
- Root mean squared error: 4.2111
- Mean absolute error: 5.3904
- R2 score: 0.8806
===================================


K-Neighbours Regression
Model performance for training set
- Root mean squared error: 4.5270
- Mean absolute error: 5.7172
- R2 score: 0.8550
----------------------
Model performace for test set
- Root mean squared error: 5.6280
- Mean absolute error: 7.2553
- R2 score: 0.7837
===================================


Decision Tree
Model performance for training set
- Root mean squared error: 0.0187
- Mean absolute error: 0.2795
- R2 score: 0.9997
----------------------
Model performace for test set
- Root mean squared error: 6.2350
- Mean absolute error: 7.9640
- R2 score: 0.7394
===================================


Random forest Regressor
Model performance for training set
- Root mean squared error: 1.8164
- Mean absolute error: 2.2814
- R2 score: 0.9769
----------------------
Model performace for test set
- Root mean squared error: 4.6339
- Mean absolute error: 5.9852
- R2 score: 0.8528
===================================


XGBoostRegressor
Model performance for training set
- Root mean squared error: 0.6875
- Mean absolute error: 1.0073
- R2 score: 0.9955
----------------------
Model performace for test set
- Root mean squared error: 5.0577
- Mean absolute error: 6.4733
- R2 score: 0.8278
===================================


Learning rate set to 0.039525
0:	learn: 14.5987177	total: 361us	remaining: 361ms
1:	learn: 14.2251886	total: 651us	remaining: 325ms
2:	learn: 13.8866124	total: 931us	remaining: 310ms
3:	learn: 13.5235688	total: 1.22ms	remaining: 303ms
4:	learn: 13.1887021	total: 1.49ms	remaining: 296ms
5:	learn: 12.9124226	total: 1.76ms	remaining: 292ms
6:	learn: 12.6000335	total: 2.02ms	remaining: 286ms
7:	learn: 12.3299057	total: 2.28ms	remaining: 282ms
8:	learn: 12.0660619	total: 2.55ms	remaining: 281ms
9:	learn: 11.7730981	total: 2.86ms	remaining: 283ms
10:	learn: 11.4922764	total: 3.19ms	remaining: 287ms
11:	learn: 11.2626483	total: 3.52ms	remaining: 290ms
12:	learn: 11.0426039	total: 3.81ms	remaining: 289ms
13:	learn: 10.7991693	total: 4.11ms	remaining: 290ms
14:	learn: 10.5541002	total: 4.52ms	remaining: 297ms
15:	learn: 10.3191811	total: 4.84ms	remaining: 297ms
16:	learn: 10.1000444	total: 5.14ms	remaining: 297ms
17:	learn: 9.8945567	total: 5.46ms	remaining: 298ms
18:	learn: 9.6901741	total: 5.76ms	remaining: 297ms
19:	learn: 9.5060349	total: 6.08ms	remaining: 298ms
20:	learn: 9.3385246	total: 6.38ms	remaining: 297ms
21:	learn: 9.1702033	total: 6.69ms	remaining: 297ms
22:	learn: 9.0103000	total: 7.01ms	remaining: 298ms
23:	learn: 8.8438667	total: 7.27ms	remaining: 296ms
24:	learn: 8.6905481	total: 7.52ms	remaining: 293ms
25:	learn: 8.5553077	total: 7.8ms	remaining: 292ms
26:	learn: 8.4138513	total: 8.05ms	remaining: 290ms
27:	learn: 8.2925602	total: 8.32ms	remaining: 289ms
28:	learn: 8.1621938	total: 8.58ms	remaining: 287ms
29:	learn: 8.0407363	total: 8.85ms	remaining: 286ms
30:	learn: 7.9212203	total: 9.45ms	remaining: 295ms
31:	learn: 7.8095890	total: 9.84ms	remaining: 298ms
32:	learn: 7.6996758	total: 10.1ms	remaining: 296ms
33:	learn: 7.6064527	total: 10.4ms	remaining: 295ms
34:	learn: 7.4988803	total: 10.6ms	remaining: 293ms
35:	learn: 7.4011587	total: 10.9ms	remaining: 291ms
36:	learn: 7.3064311	total: 11.1ms	remaining: 290ms
37:	learn: 7.2238635	total: 11.4ms	remaining: 288ms
38:	learn: 7.1434777	total: 11.7ms	remaining: 289ms
39:	learn: 7.0628171	total: 12ms	remaining: 289ms
40:	learn: 6.9907934	total: 12.3ms	remaining: 288ms
41:	learn: 6.9318622	total: 12.6ms	remaining: 287ms
42:	learn: 6.8582966	total: 12.9ms	remaining: 287ms
43:	learn: 6.7862682	total: 13.2ms	remaining: 286ms
44:	learn: 6.7171185	total: 13.5ms	remaining: 286ms
45:	learn: 6.6529481	total: 13.7ms	remaining: 285ms
46:	learn: 6.5896861	total: 14ms	remaining: 285ms
47:	learn: 6.5312831	total: 14.3ms	remaining: 285ms
48:	learn: 6.4713680	total: 14.7ms	remaining: 286ms
49:	learn: 6.4164814	total: 15ms	remaining: 285ms
50:	learn: 6.3698708	total: 15.3ms	remaining: 284ms
51:	learn: 6.3256781	total: 15.5ms	remaining: 283ms
52:	learn: 6.2757661	total: 15.8ms	remaining: 282ms
53:	learn: 6.2247740	total: 16.1ms	remaining: 281ms
54:	learn: 6.1822493	total: 16.3ms	remaining: 281ms
55:	learn: 6.1399042	total: 16.6ms	remaining: 280ms
56:	learn: 6.1005255	total: 16.9ms	remaining: 279ms
57:	learn: 6.0625686	total: 17.2ms	remaining: 279ms
58:	learn: 6.0305593	total: 17.4ms	remaining: 278ms
59:	learn: 5.9979314	total: 17.7ms	remaining: 278ms
60:	learn: 5.9641038	total: 18ms	remaining: 277ms
61:	learn: 5.9337297	total: 18.3ms	remaining: 277ms
62:	learn: 5.9019327	total: 18.6ms	remaining: 277ms
63:	learn: 5.8737278	total: 18.9ms	remaining: 276ms
64:	learn: 5.8464857	total: 19.2ms	remaining: 276ms
65:	learn: 5.8206309	total: 19.5ms	remaining: 275ms
66:	learn: 5.7936462	total: 19.8ms	remaining: 275ms
67:	learn: 5.7653886	total: 20ms	remaining: 275ms
68:	learn: 5.7470739	total: 20.3ms	remaining: 274ms
69:	learn: 5.7223152	total: 20.6ms	remaining: 273ms
70:	learn: 5.6999706	total: 20.8ms	remaining: 272ms
71:	learn: 5.6827326	total: 21.1ms	remaining: 272ms
72:	learn: 5.6635258	total: 21.4ms	remaining: 271ms
73:	learn: 5.6423816	total: 21.7ms	remaining: 271ms
74:	learn: 5.6214048	total: 22ms	remaining: 271ms
75:	learn: 5.6024601	total: 22.3ms	remaining: 271ms
76:	learn: 5.5873376	total: 22.6ms	remaining: 271ms
77:	learn: 5.5723930	total: 23ms	remaining: 271ms
78:	learn: 5.5584258	total: 23.2ms	remaining: 271ms
79:	learn: 5.5415189	total: 23.5ms	remaining: 271ms
80:	learn: 5.5261573	total: 23.9ms	remaining: 271ms
81:	learn: 5.5117470	total: 24.1ms	remaining: 270ms
82:	learn: 5.5049750	total: 24.2ms	remaining: 268ms
83:	learn: 5.4939805	total: 24.6ms	remaining: 268ms
84:	learn: 5.4807455	total: 24.8ms	remaining: 267ms
85:	learn: 5.4640520	total: 25.2ms	remaining: 267ms
86:	learn: 5.4491437	total: 25.5ms	remaining: 268ms
87:	learn: 5.4382554	total: 25.8ms	remaining: 267ms
88:	learn: 5.4259279	total: 26.1ms	remaining: 267ms
89:	learn: 5.4123312	total: 26.4ms	remaining: 267ms
90:	learn: 5.4006915	total: 26.9ms	remaining: 268ms
91:	learn: 5.3916187	total: 27.2ms	remaining: 268ms
92:	learn: 5.3807666	total: 27.4ms	remaining: 268ms
93:	learn: 5.3722072	total: 27.7ms	remaining: 267ms
94:	learn: 5.3629188	total: 28ms	remaining: 267ms
95:	learn: 5.3482923	total: 28.3ms	remaining: 267ms
96:	learn: 5.3397723	total: 28.6ms	remaining: 266ms
97:	learn: 5.3315160	total: 28.9ms	remaining: 266ms
98:	learn: 5.3238616	total: 29.2ms	remaining: 265ms
99:	learn: 5.3132773	total: 29.5ms	remaining: 265ms
100:	learn: 5.3068563	total: 29.8ms	remaining: 265ms
101:	learn: 5.2965206	total: 30.1ms	remaining: 265ms
102:	learn: 5.2883508	total: 30.4ms	remaining: 265ms
103:	learn: 5.2799335	total: 30.7ms	remaining: 264ms
104:	learn: 5.2717891	total: 31ms	remaining: 264ms
105:	learn: 5.2626847	total: 31.2ms	remaining: 263ms
106:	learn: 5.2516198	total: 31.6ms	remaining: 264ms
107:	learn: 5.2410122	total: 31.9ms	remaining: 264ms
108:	learn: 5.2326840	total: 32.2ms	remaining: 263ms
109:	learn: 5.2242671	total: 32.5ms	remaining: 263ms
110:	learn: 5.2163250	total: 32.8ms	remaining: 263ms
111:	learn: 5.2111025	total: 33.1ms	remaining: 263ms
112:	learn: 5.2063643	total: 33.4ms	remaining: 262ms
113:	learn: 5.1969376	total: 33.6ms	remaining: 261ms
114:	learn: 5.1907460	total: 33.9ms	remaining: 261ms
115:	learn: 5.1818852	total: 34.2ms	remaining: 261ms
116:	learn: 5.1782936	total: 34.5ms	remaining: 260ms
117:	learn: 5.1709914	total: 34.8ms	remaining: 260ms
118:	learn: 5.1662572	total: 35.1ms	remaining: 260ms
119:	learn: 5.1614212	total: 35.4ms	remaining: 260ms
120:	learn: 5.1582235	total: 35.7ms	remaining: 259ms
121:	learn: 5.1547099	total: 35.9ms	remaining: 258ms
122:	learn: 5.1463881	total: 36.2ms	remaining: 258ms
123:	learn: 5.1395294	total: 36.5ms	remaining: 258ms
124:	learn: 5.1342760	total: 36.8ms	remaining: 258ms
125:	learn: 5.1285361	total: 37.1ms	remaining: 257ms
126:	learn: 5.1233004	total: 37.3ms	remaining: 256ms
127:	learn: 5.1162005	total: 37.6ms	remaining: 256ms
128:	learn: 5.1087287	total: 37.9ms	remaining: 256ms
129:	learn: 5.1040759	total: 38.2ms	remaining: 256ms
130:	learn: 5.1003176	total: 38.6ms	remaining: 256ms
131:	learn: 5.0958142	total: 38.9ms	remaining: 255ms
132:	learn: 5.0921469	total: 39.1ms	remaining: 255ms
133:	learn: 5.0852583	total: 39.4ms	remaining: 255ms
134:	learn: 5.0792194	total: 39.7ms	remaining: 254ms
135:	learn: 5.0764768	total: 40ms	remaining: 254ms
136:	learn: 5.0721339	total: 40.2ms	remaining: 253ms
137:	learn: 5.0670316	total: 40.5ms	remaining: 253ms
138:	learn: 5.0613583	total: 40.8ms	remaining: 253ms
139:	learn: 5.0567591	total: 41.1ms	remaining: 253ms
140:	learn: 5.0502540	total: 41.4ms	remaining: 252ms
141:	learn: 5.0483765	total: 41.5ms	remaining: 251ms
142:	learn: 5.0426038	total: 41.8ms	remaining: 251ms
143:	learn: 5.0374773	total: 42.1ms	remaining: 250ms
144:	learn: 5.0323049	total: 42.4ms	remaining: 250ms
145:	learn: 5.0259762	total: 42.8ms	remaining: 250ms
146:	learn: 5.0195245	total: 43ms	remaining: 250ms
147:	learn: 5.0175694	total: 43.3ms	remaining: 249ms
148:	learn: 5.0089624	total: 43.6ms	remaining: 249ms
149:	learn: 5.0038803	total: 43.9ms	remaining: 248ms
150:	learn: 4.9963876	total: 44.2ms	remaining: 248ms
151:	learn: 4.9933617	total: 44.5ms	remaining: 248ms
152:	learn: 4.9900575	total: 44.7ms	remaining: 248ms
153:	learn: 4.9869088	total: 45ms	remaining: 247ms
154:	learn: 4.9852072	total: 45.3ms	remaining: 247ms
155:	learn: 4.9790035	total: 45.6ms	remaining: 247ms
156:	learn: 4.9731422	total: 45.9ms	remaining: 246ms
157:	learn: 4.9670567	total: 46.2ms	remaining: 246ms
158:	learn: 4.9614607	total: 46.4ms	remaining: 246ms
159:	learn: 4.9542404	total: 46.7ms	remaining: 245ms
160:	learn: 4.9523207	total: 46.8ms	remaining: 244ms
161:	learn: 4.9483378	total: 47.1ms	remaining: 244ms
162:	learn: 4.9432286	total: 47.4ms	remaining: 243ms
163:	learn: 4.9385458	total: 47.8ms	remaining: 244ms
164:	learn: 4.9353306	total: 48.1ms	remaining: 243ms
165:	learn: 4.9320515	total: 48.3ms	remaining: 243ms
166:	learn: 4.9289642	total: 48.6ms	remaining: 242ms
167:	learn: 4.9228602	total: 48.9ms	remaining: 242ms
168:	learn: 4.9176688	total: 49.3ms	remaining: 242ms
169:	learn: 4.9103654	total: 49.5ms	remaining: 242ms
170:	learn: 4.9064572	total: 49.9ms	remaining: 242ms
171:	learn: 4.9019965	total: 50.2ms	remaining: 241ms
172:	learn: 4.8968162	total: 50.5ms	remaining: 241ms
173:	learn: 4.8911231	total: 50.8ms	remaining: 241ms
174:	learn: 4.8876302	total: 51ms	remaining: 241ms
175:	learn: 4.8852597	total: 51.3ms	remaining: 240ms
176:	learn: 4.8806597	total: 51.6ms	remaining: 240ms
177:	learn: 4.8772997	total: 51.9ms	remaining: 240ms
178:	learn: 4.8740388	total: 52.2ms	remaining: 239ms
179:	learn: 4.8694370	total: 52.5ms	remaining: 239ms
180:	learn: 4.8612687	total: 52.8ms	remaining: 239ms
181:	learn: 4.8586731	total: 53.1ms	remaining: 239ms
182:	learn: 4.8540362	total: 53.4ms	remaining: 238ms
183:	learn: 4.8513024	total: 53.7ms	remaining: 238ms
184:	learn: 4.8475101	total: 54.1ms	remaining: 238ms
185:	learn: 4.8456917	total: 54.4ms	remaining: 238ms
186:	learn: 4.8420586	total: 54.7ms	remaining: 238ms
187:	learn: 4.8386237	total: 54.9ms	remaining: 237ms
188:	learn: 4.8346022	total: 55.3ms	remaining: 237ms
189:	learn: 4.8308590	total: 55.5ms	remaining: 237ms
190:	learn: 4.8275905	total: 55.8ms	remaining: 236ms
191:	learn: 4.8222462	total: 56.1ms	remaining: 236ms
192:	learn: 4.8166864	total: 56.3ms	remaining: 236ms
193:	learn: 4.8147971	total: 56.6ms	remaining: 235ms
194:	learn: 4.8116394	total: 56.9ms	remaining: 235ms
195:	learn: 4.8048134	total: 57.3ms	remaining: 235ms
196:	learn: 4.8025161	total: 57.6ms	remaining: 235ms
197:	learn: 4.8000879	total: 57.8ms	remaining: 234ms
198:	learn: 4.7947731	total: 58.1ms	remaining: 234ms
199:	learn: 4.7916648	total: 58.4ms	remaining: 233ms
200:	learn: 4.7859899	total: 58.6ms	remaining: 233ms
201:	learn: 4.7823871	total: 58.9ms	remaining: 233ms
202:	learn: 4.7786237	total: 59.2ms	remaining: 232ms
203:	learn: 4.7757722	total: 59.5ms	remaining: 232ms
204:	learn: 4.7702310	total: 59.8ms	remaining: 232ms
205:	learn: 4.7644967	total: 60.1ms	remaining: 232ms
206:	learn: 4.7631387	total: 60.4ms	remaining: 231ms
207:	learn: 4.7580533	total: 60.7ms	remaining: 231ms
208:	learn: 4.7550638	total: 60.9ms	remaining: 231ms
209:	learn: 4.7524653	total: 61.2ms	remaining: 230ms
210:	learn: 4.7480674	total: 61.5ms	remaining: 230ms
211:	learn: 4.7441633	total: 61.8ms	remaining: 230ms
212:	learn: 4.7366709	total: 62.1ms	remaining: 229ms
213:	learn: 4.7334926	total: 62.4ms	remaining: 229ms
214:	learn: 4.7318646	total: 62.7ms	remaining: 229ms
215:	learn: 4.7283983	total: 63ms	remaining: 229ms
216:	learn: 4.7238660	total: 63.2ms	remaining: 228ms
217:	learn: 4.7234834	total: 63.5ms	remaining: 228ms
218:	learn: 4.7209542	total: 63.8ms	remaining: 228ms
219:	learn: 4.7161734	total: 64.1ms	remaining: 227ms
220:	learn: 4.7105640	total: 64.4ms	remaining: 227ms
221:	learn: 4.7071603	total: 64.6ms	remaining: 227ms
222:	learn: 4.7040835	total: 64.9ms	remaining: 226ms
223:	learn: 4.7025018	total: 65.2ms	remaining: 226ms
224:	learn: 4.7002697	total: 65.5ms	remaining: 226ms
225:	learn: 4.6953463	total: 65.8ms	remaining: 225ms
226:	learn: 4.6897693	total: 66ms	remaining: 225ms
227:	learn: 4.6879195	total: 66.4ms	remaining: 225ms
228:	learn: 4.6829821	total: 66.6ms	remaining: 224ms
229:	learn: 4.6795787	total: 66.9ms	remaining: 224ms
230:	learn: 4.6757514	total: 67.2ms	remaining: 224ms
231:	learn: 4.6727107	total: 67.5ms	remaining: 223ms
232:	learn: 4.6690533	total: 67.8ms	remaining: 223ms
233:	learn: 4.6675957	total: 68ms	remaining: 223ms
234:	learn: 4.6642413	total: 68.3ms	remaining: 222ms
235:	learn: 4.6622470	total: 68.6ms	remaining: 222ms
236:	learn: 4.6586684	total: 68.9ms	remaining: 222ms
237:	learn: 4.6580176	total: 69.2ms	remaining: 221ms
238:	learn: 4.6576567	total: 69.4ms	remaining: 221ms
239:	learn: 4.6532429	total: 69.7ms	remaining: 221ms
240:	learn: 4.6507302	total: 70ms	remaining: 220ms
241:	learn: 4.6476713	total: 70.3ms	remaining: 220ms
242:	learn: 4.6455060	total: 70.6ms	remaining: 220ms
243:	learn: 4.6412979	total: 70.9ms	remaining: 220ms
244:	learn: 4.6379811	total: 71.2ms	remaining: 219ms
245:	learn: 4.6350623	total: 71.4ms	remaining: 219ms
246:	learn: 4.6316060	total: 71.7ms	remaining: 219ms
247:	learn: 4.6302155	total: 72ms	remaining: 218ms
248:	learn: 4.6272981	total: 72.2ms	remaining: 218ms
249:	learn: 4.6246918	total: 72.6ms	remaining: 218ms
250:	learn: 4.6218401	total: 72.8ms	remaining: 217ms
251:	learn: 4.6196021	total: 73.1ms	remaining: 217ms
252:	learn: 4.6135840	total: 73.4ms	remaining: 217ms
253:	learn: 4.6119388	total: 73.7ms	remaining: 216ms
254:	learn: 4.6087070	total: 74ms	remaining: 216ms
255:	learn: 4.6047716	total: 74.3ms	remaining: 216ms
256:	learn: 4.6042313	total: 74.6ms	remaining: 216ms
257:	learn: 4.6007504	total: 74.9ms	remaining: 216ms
258:	learn: 4.5964883	total: 75.2ms	remaining: 215ms
259:	learn: 4.5947078	total: 75.5ms	remaining: 215ms
260:	learn: 4.5888180	total: 75.8ms	remaining: 215ms
261:	learn: 4.5850542	total: 76ms	remaining: 214ms
262:	learn: 4.5814714	total: 76.3ms	remaining: 214ms
263:	learn: 4.5775552	total: 76.6ms	remaining: 214ms
264:	learn: 4.5745714	total: 76.9ms	remaining: 213ms
265:	learn: 4.5730292	total: 77.2ms	remaining: 213ms
266:	learn: 4.5713262	total: 77.5ms	remaining: 213ms
267:	learn: 4.5710192	total: 77.7ms	remaining: 212ms
268:	learn: 4.5657666	total: 78ms	remaining: 212ms
269:	learn: 4.5633835	total: 78.3ms	remaining: 212ms
270:	learn: 4.5581658	total: 78.6ms	remaining: 211ms
271:	learn: 4.5562921	total: 78.9ms	remaining: 211ms
272:	learn: 4.5493838	total: 79.1ms	remaining: 211ms
273:	learn: 4.5462275	total: 79.4ms	remaining: 210ms
274:	learn: 4.5406210	total: 79.7ms	remaining: 210ms
275:	learn: 4.5328982	total: 80ms	remaining: 210ms
276:	learn: 4.5297574	total: 80.3ms	remaining: 209ms
277:	learn: 4.5257929	total: 80.5ms	remaining: 209ms
278:	learn: 4.5215722	total: 80.8ms	remaining: 209ms
279:	learn: 4.5188181	total: 81.1ms	remaining: 209ms
280:	learn: 4.5140123	total: 81.4ms	remaining: 208ms
281:	learn: 4.5083314	total: 81.6ms	remaining: 208ms
282:	learn: 4.5060385	total: 81.9ms	remaining: 208ms
283:	learn: 4.5058056	total: 82.2ms	remaining: 207ms
284:	learn: 4.5015504	total: 82.5ms	remaining: 207ms
285:	learn: 4.4946926	total: 82.7ms	remaining: 206ms
286:	learn: 4.4893302	total: 83ms	remaining: 206ms
287:	learn: 4.4848270	total: 83.2ms	remaining: 206ms
288:	learn: 4.4782854	total: 83.5ms	remaining: 205ms
289:	learn: 4.4753117	total: 83.8ms	remaining: 205ms
290:	learn: 4.4715813	total: 84ms	remaining: 205ms
291:	learn: 4.4691650	total: 84.4ms	remaining: 205ms
292:	learn: 4.4620680	total: 84.6ms	remaining: 204ms
293:	learn: 4.4585410	total: 84.9ms	remaining: 204ms
294:	learn: 4.4557575	total: 85.2ms	remaining: 204ms
295:	learn: 4.4530274	total: 85.5ms	remaining: 203ms
296:	learn: 4.4506593	total: 85.7ms	remaining: 203ms
297:	learn: 4.4446969	total: 86ms	remaining: 203ms
298:	learn: 4.4420528	total: 86.3ms	remaining: 202ms
299:	learn: 4.4400368	total: 86.6ms	remaining: 202ms
300:	learn: 4.4350171	total: 86.9ms	remaining: 202ms
301:	learn: 4.4299621	total: 87.1ms	remaining: 201ms
302:	learn: 4.4276663	total: 87.4ms	remaining: 201ms
303:	learn: 4.4250300	total: 87.8ms	remaining: 201ms
304:	learn: 4.4225888	total: 88ms	remaining: 201ms
305:	learn: 4.4189367	total: 88.3ms	remaining: 200ms
306:	learn: 4.4168880	total: 88.5ms	remaining: 200ms
307:	learn: 4.4137734	total: 88.9ms	remaining: 200ms
308:	learn: 4.4111294	total: 89.2ms	remaining: 199ms
309:	learn: 4.4085082	total: 89.5ms	remaining: 199ms
310:	learn: 4.4048803	total: 89.7ms	remaining: 199ms
311:	learn: 4.4045938	total: 90ms	remaining: 198ms
312:	learn: 4.4021399	total: 90.3ms	remaining: 198ms
313:	learn: 4.4002847	total: 90.5ms	remaining: 198ms
314:	learn: 4.3958055	total: 90.8ms	remaining: 198ms
315:	learn: 4.3928388	total: 91.1ms	remaining: 197ms
316:	learn: 4.3892131	total: 91.4ms	remaining: 197ms
317:	learn: 4.3861981	total: 91.7ms	remaining: 197ms
318:	learn: 4.3850542	total: 92ms	remaining: 196ms
319:	learn: 4.3793646	total: 92.3ms	remaining: 196ms
320:	learn: 4.3783876	total: 92.5ms	remaining: 196ms
321:	learn: 4.3758167	total: 92.8ms	remaining: 195ms
322:	learn: 4.3746002	total: 93.1ms	remaining: 195ms
323:	learn: 4.3709890	total: 93.4ms	remaining: 195ms
324:	learn: 4.3674185	total: 93.7ms	remaining: 195ms
325:	learn: 4.3635846	total: 94ms	remaining: 194ms
326:	learn: 4.3607707	total: 94.3ms	remaining: 194ms
327:	learn: 4.3586758	total: 94.6ms	remaining: 194ms
328:	learn: 4.3542282	total: 94.8ms	remaining: 193ms
329:	learn: 4.3537734	total: 95.1ms	remaining: 193ms
330:	learn: 4.3516480	total: 95.4ms	remaining: 193ms
331:	learn: 4.3482099	total: 95.7ms	remaining: 193ms
332:	learn: 4.3458527	total: 96ms	remaining: 192ms
333:	learn: 4.3423734	total: 96.3ms	remaining: 192ms
334:	learn: 4.3408144	total: 96.6ms	remaining: 192ms
335:	learn: 4.3397071	total: 96.9ms	remaining: 192ms
336:	learn: 4.3354308	total: 97.2ms	remaining: 191ms
337:	learn: 4.3352189	total: 97.5ms	remaining: 191ms
338:	learn: 4.3285072	total: 97.8ms	remaining: 191ms